apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elastic-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/service.serversscheme: https
    traefik.ingress.kubernetes.io/frontend-entry-points: https
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - host: elastic.becloud.ro
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kubeclarity-kubeclarity
            port:
              number: 8080
  tls:
    - secretName: elastic-tls
      hosts:
        - elastic.becloud.ro
