apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nexus
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: nexus
    server: ''
  source:
    path: ingress/nexus
    repoURL: 'https://github.com/insightcloud/devops.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
